apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p7jjjv5tv-python 
  janus-idp.io/tekton: p7jjjv5tv-python
  backstage.io/kubernetes-id: p7jjjv5tv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p7jjjv5tv-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  